# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-19 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
